buddies = [
    {
        "id": 1,
        "name": "Alice Johnson",
        "role": "UX Designer",
        "interests": ["Product Design", "Figma", "Design Systems"],
        "status": "Available",
        "bio": "I craft intuitive experiences that bridge user needs and business goals.",
        "match": 92,
    },
    {
        "id": 2,
        "name": "Marcus Lee",
        "role": "Backend Engineer",
        "interests": ["Open Source", "Distributed Systems"],
        "status": "Available",
        "bio": "Building scalable systems and contributing to open-source ecosystems.",
        "match": 87,
    },
    {
        "id": 3,
        "name": "Sofia Ramirez",
        "role": "Data Scientist",
        "interests": ["Machine Learning", "Python", "Data Viz"],
        "status": "Available",
        "bio": "Turning raw data into actionable insights with ML and statistical modeling.",
        "match": 84,
    },
    {
        "id": 4,
        "name": "James Okafor",
        "role": "Frontend Developer",
        "interests": ["Web Accessibility", "React"],
        "status": "Available",
        "bio": "Passionate about building inclusive web experiences for everyone.",
        "match": 79,
    },
    {
        "id": 5,
        "name": "Yuki Tanaka",
        "role": "Product Manager",
        "interests": ["Agile & Scrum", "Roadmapping", "User Research"],
        "status": "Available",
        "bio": "Shipping products users love by bridging business and engineering.",
        "match": 76,
    },
    {
        "id": 6,
        "name": "Priya Nair",
        "role": "Full Stack Developer",
        "interests": ["Cloud Architecture", "Kubernetes"],
        "status": "Available",
        "bio": "Designing and deploying resilient cloud-native applications at scale.",
        "match": 73,
    },
    {
        "id": 7,
        "name": "Carlos Mendez",
        "role": "Mobile Developer",
        "interests": ["React Native", "iOS", "Flutter"],
        "status": "Available",
        "bio": "Building cross-platform mobile apps with a focus on performance and UX.",
        "match": 68,
    },
    {
        "id": 8,
        "name": "Emma Schulz",
        "role": "DevOps Engineer",
        "interests": ["CI/CD Pipelines", "Terraform"],
        "status": "Available",
        "bio": "Automating delivery pipelines and fostering a strong DevOps culture.",
        "match": 65,
    },
    {
        "id": 9,
        "name": "Lena Fischer",
        "role": "Graphic Designer",
        "interests": ["Brand Identity", "Motion Design", "Typography"],
        "status": "Available",
        "bio": "Shaping brand voices through bold visual storytelling and design systems.",
        "match": 63,
    },
    {
        "id": 10,
        "name": "Amir Hosseini",
        "role": "Cybersecurity Analyst",
        "interests": ["Ethical Hacking", "Penetration Testing"],
        "status": "Available",
        "bio": "Protecting systems by thinking like an attacker and building resilient defenses.",
        "match": 61,
    },
    {
        "id": 11,
        "name": "Nina Petrov",
        "role": "AI/ML Engineer",
        "interests": ["Generative AI", "NLP", "PyTorch"],
        "status": "Available",
        "bio": "Pushing the boundaries of what models can create, reason, and understand.",
        "match": 59,
    },
    {
        "id": 12,
        "name": "David Kim",
        "role": "Blockchain Developer",
        "interests": ["Web3 & DeFi", "Smart Contracts"],
        "status": "Available",
        "bio": "Building decentralized protocols that redefine trust and finance.",
        "match": 57,
    },
    {
        "id": 13,
        "name": "Amara Diallo",
        "role": "Growth Marketer",
        "interests": ["SEO & Content", "Analytics", "Copywriting"],
        "status": "Available",
        "bio": "Driving organic growth through data-informed content and marketing funnels.",
        "match": 55,
    },
    {
        "id": 14,
        "name": "Lucas Oliveira",
        "role": "Game Developer",
        "interests": ["Unity & Unreal", "3D Modeling"],
        "status": "Available",
        "bio": "Crafting immersive gameplay experiences from concept to launch.",
        "match": 53,
    },
    {
        "id": 15,
        "name": "Sara Lindqvist",
        "role": "Research Scientist",
        "interests": ["Computational Biology", "Bioinformatics", "R"],
        "status": "Available",
        "bio": "Applying algorithms to unravel complex biological systems and genomic data.",
        "match": 51,
    },
    {
        "id": 16,
        "name": "Omar Hassan",
        "role": "Embedded Systems Engineer",
        "interests": ["IoT & Firmware", "C/C++"],
        "status": "Available",
        "bio": "Bridging hardware and software to build smart, connected devices.",
        "match": 49,
    },
    {
        "id": 17,
        "name": "Mei Chen",
        "role": "Technical Writer",
        "interests": ["Developer Docs", "API Design", "Markdown"],
        "status": "Available",
        "bio": "Turning complex technical concepts into clear, developer-friendly documentation.",
        "match": 47,
    },
    {
        "id": 18,
        "name": "Ethan Brooks",
        "role": "Solutions Architect",
        "interests": ["System Design", "AWS"],
        "status": "Available",
        "bio": "Designing large-scale distributed systems that stay reliable under pressure.",
        "match": 45,
    },
    {
        "id": 19,
        "name": "Isabella Rossi",
        "role": "AR/VR Developer",
        "interests": ["Spatial Computing", "WebXR", "3D UI"],
        "status": "Available",
        "bio": "Building the next layer of the internet through immersive spatial experiences.",
        "match": 43,
    },
    {
        "id": 20,
        "name": "Kwame Asante",
        "role": "Startup Founder",
        "interests": ["VC & Fundraising", "Lean Startup"],
        "status": "Available",
        "bio": "Building from zero to one and navigating the early-stage startup journey.",
        "match": 41,
    },
]
